# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hue' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 4.0'
  # Pods for Hue

  target 'HueTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HueUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
